FROM alpine:3.20 AS builder
WORKDIR /build
COPY frontend/ ./
COPY nginx/default.conf /tmp/default.conf

FROM nginx:alpine
COPY --from=builder /build /usr/share/nginx/html
COPY --from=builder /tmp/default.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /var/cache/nginx/product_dashboard

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]